//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BindingData.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BindingData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstname        ///Aaron        ///Aaron        ///Abbey        ///Abbie        ///Abby        ///Abdul        ///Abe        ///Abel        ///Abigail        ///Abraham        ///Abram        ///Ada        ///Adah        ///Adalberto        ///Adaline        ///Adam        ///Adam        ///Adan        ///Addie        ///Adela        ///Adelaida        ///Adelaide        ///Adele        ///Adelia        ///Adelina        ///Adeline        ///Adell        ///Adella        ///Adelle        ///Adena        ///Adina        ///Adolfo        ///Adolph        ///Adria        ///Adrian        ///Adrian        ///Adriana        ///Adriane        ///Adrianna        ///Adrianne        ///Adrien        ///Adriene        ///Adrienne        ///Afton        ///Agatha        ///Agnes        ///Agnus        ///Agripina        ///Agueda        ///Agustin        ///Agustina        ///Ahmad        ///Ahmed        ///Ai        ///Aida        ///Aide        ///Aiko        ///Aileen        ///Ailene        ///Aimee        ///Aisha        ///Aja        ///Akiko        ///Akilah        ///Al        ///Alaina        ///Alaine        ///Alan        ///Alana        ///Alane        ///Alanna        ///Alayna        ///Alba        ///Albert        ///Albert        ///Alberta        ///Alber [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSV_Database_of_First_Names {
            get {
                return ResourceManager.GetString("CSV_Database_of_First_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastname        ///Aaberg        ///Aaby        ///Aadland        ///Aagaard        ///Aakre        ///Aaland        ///Aalbers        ///Aalderink        ///Aalund        ///Aamodt        ///Aamot        ///Aanderud        ///Aanenson        ///Aanerud        ///Aarant        ///Aardema        ///Aarestad        ///Aarhus        ///Aaron        ///Aarons        ///Aaronson        ///Aarsvold        ///Aas        ///Aasby        ///Aase        ///Aasen        ///Aavang        ///Abad        ///Abadi        ///Abadie        ///Abair        ///Abaja        ///Abajian        ///Abalos        ///Abaloz        ///Abar        ///Abarca        ///Abare        ///Abascal        ///Abasta        ///Abate        ///Abati        ///Abatiell        ///Abato        ///Abatti        ///Abaunza        ///Abaya        ///Abbadessa        ///Abbamonte        ///Abbas        ///Abbasi        ///Abbassi        ///Abbate        ///Abbatiello        ///Abbay        ///Abbe        ///Abbed        ///Abbenante        ///Abbey        ///Abbinanti        ///Abbington        ///Abbitt        ///Abbot        ///Abbott        ///Abboud        ///Abbruzzese        ///Abbs        ///Abby        ///Abdalla        ///Abdalla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSV_Database_of_Last_Names {
            get {
                return ResourceManager.GetString("CSV_Database_of_Last_Names", resourceCulture);
            }
        }
    }
}
