// <auto-generated />
namespace EcommerceSite1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MadeFormFieldsRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MadeFormFieldsRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201711102115561_MadeFormFieldsRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
